/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site_old': RouteRecordInfo<
      '/about/site_old',
      '/about/site_old',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/abstract': RouteRecordInfo<
      '/albums/abstract',
      '/albums/abstract',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/animals': RouteRecordInfo<
      '/albums/animals',
      '/albums/animals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/ff14': RouteRecordInfo<
      '/albums/ff14',
      '/albums/ff14',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/GEZONE': RouteRecordInfo<
      '/albums/GEZONE',
      '/albums/GEZONE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/green': RouteRecordInfo<
      '/albums/green',
      '/albums/green',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/lives': RouteRecordInfo<
      '/albums/lives',
      '/albums/lives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/objects': RouteRecordInfo<
      '/albums/objects',
      '/albums/objects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/sky': RouteRecordInfo<
      '/albums/sky',
      '/albums/sky',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/water': RouteRecordInfo<
      '/albums/water',
      '/albums/water',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/anime/': RouteRecordInfo<
      '/anime/',
      '/anime',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/': RouteRecordInfo<
      '/moments/',
      '/moments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/2026-08-17-moments': RouteRecordInfo<
      '/moments/2026-08-17-moments',
      '/moments/2026-08-17-moments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/2026-08-19-cullumi-video': RouteRecordInfo<
      '/moments/2026-08-19-cullumi-video',
      '/moments/2026-08-19-cullumi-video',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/2026-09-04-1': RouteRecordInfo<
      '/moments/2026-09-04-1',
      '/moments/2026-09-04-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments/2026-09-05-1': RouteRecordInfo<
      '/moments/2026-09-05-1',
      '/moments/2026-09-05-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ADFGVXCypher': RouteRecordInfo<
      '/posts/ADFGVXCypher',
      '/posts/ADFGVXCypher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bigDataVisualization': RouteRecordInfo<
      '/posts/bigDataVisualization',
      '/posts/bigDataVisualization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/booksSearch': RouteRecordInfo<
      '/posts/booksSearch',
      '/posts/booksSearch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cullumi': RouteRecordInfo<
      '/posts/cullumi',
      '/posts/cullumi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ffhouse': RouteRecordInfo<
      '/posts/ffhouse',
      '/posts/ffhouse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ffLadiesDay': RouteRecordInfo<
      '/posts/ffLadiesDay',
      '/posts/ffLadiesDay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/getColor': RouteRecordInfo<
      '/posts/getColor',
      '/posts/getColor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GEZONE': RouteRecordInfo<
      '/posts/GEZONE',
      '/posts/GEZONE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/LLsif': RouteRecordInfo<
      '/posts/LLsif',
      '/posts/LLsif',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/oskarstalbergsGame': RouteRecordInfo<
      '/posts/oskarstalbergsGame',
      '/posts/oskarstalbergsGame',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pageBuilding': RouteRecordInfo<
      '/posts/pageBuilding',
      '/posts/pageBuilding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/photography': RouteRecordInfo<
      '/posts/photography',
      '/posts/photography',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/slidev': RouteRecordInfo<
      '/posts/slidev',
      '/posts/slidev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/smallCCompiler': RouteRecordInfo<
      '/posts/smallCCompiler',
      '/posts/smallCCompiler',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/songs': RouteRecordInfo<
      '/posts/songs',
      '/posts/songs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/stars': RouteRecordInfo<
      '/posts/stars',
      '/posts/stars',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/testEchart': RouteRecordInfo<
      '/posts/testEchart',
      '/posts/testEchart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy': RouteRecordInfo<
      '/posts/valaxy',
      '/posts/valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.9_magicast@0.5.4_valaxy@1.0.0-rc.9_@babel+parser@7.29.8_@nuxt_e3d816dcb7e2f757b604b7590c2532d9/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-rc.9_@babel+parser@7.29.8_@nuxt+kit@3.21.11_magicast@0.5.4__@types+markdow_b0d0cc906d2c05ae3ed876ae04b5235e/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/about/site_old.md': {
      routes:
        | '/about/site_old'
      views:
        | never
    }
    'pages/albums/index.md': {
      routes:
        | '/albums/'
      views:
        | never
    }
    'pages/albums/abstract.md': {
      routes:
        | '/albums/abstract'
      views:
        | never
    }
    'pages/albums/animals.md': {
      routes:
        | '/albums/animals'
      views:
        | never
    }
    'pages/albums/ff14.md': {
      routes:
        | '/albums/ff14'
      views:
        | never
    }
    'pages/albums/GEZONE.md': {
      routes:
        | '/albums/GEZONE'
      views:
        | never
    }
    'pages/albums/green.md': {
      routes:
        | '/albums/green'
      views:
        | never
    }
    'pages/albums/lives.md': {
      routes:
        | '/albums/lives'
      views:
        | never
    }
    'pages/albums/objects.md': {
      routes:
        | '/albums/objects'
      views:
        | never
    }
    'pages/albums/sky.md': {
      routes:
        | '/albums/sky'
      views:
        | never
    }
    'pages/albums/water.md': {
      routes:
        | '/albums/water'
      views:
        | never
    }
    'pages/anime/index.md': {
      routes:
        | '/anime/'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-addon-moments@0.1.4_valaxy@1.0.0-rc.9_@babel+parser@7.29.8_@nuxt+kit@3.21.11_mag_eeee8933481b3af243d6feb66a58afb6/node_modules/valaxy-addon-moments/pages/moments/index.vue': {
      routes:
        | '/moments/'
      views:
        | never
    }
    'pages/moments/2026-08-17-moments.md': {
      routes:
        | '/moments/2026-08-17-moments'
      views:
        | never
    }
    'pages/moments/2026-08-19-cullumi-video.md': {
      routes:
        | '/moments/2026-08-19-cullumi-video'
      views:
        | never
    }
    'pages/moments/2026-09-04-1.md': {
      routes:
        | '/moments/2026-09-04-1'
      views:
        | never
    }
    'pages/moments/2026-09-05-1.md': {
      routes:
        | '/moments/2026-09-05-1'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.9_magicast@0.5.4_valaxy@1.0.0-rc.9_@babel+parser@7.29.8_@nuxt_e3d816dcb7e2f757b604b7590c2532d9/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.9_magicast@0.5.4_valaxy@1.0.0-rc.9_@babel+parser@7.29.8_@nuxt_e3d816dcb7e2f757b604b7590c2532d9/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/ADFGVXCypher.md': {
      routes:
        | '/posts/ADFGVXCypher'
      views:
        | never
    }
    'pages/posts/bigDataVisualization.md': {
      routes:
        | '/posts/bigDataVisualization'
      views:
        | never
    }
    'pages/posts/booksSearch.md': {
      routes:
        | '/posts/booksSearch'
      views:
        | never
    }
    'pages/posts/cullumi.md': {
      routes:
        | '/posts/cullumi'
      views:
        | never
    }
    'pages/posts/ffhouse.md': {
      routes:
        | '/posts/ffhouse'
      views:
        | never
    }
    'pages/posts/ffLadiesDay.md': {
      routes:
        | '/posts/ffLadiesDay'
      views:
        | never
    }
    'pages/posts/getColor.md': {
      routes:
        | '/posts/getColor'
      views:
        | never
    }
    'pages/posts/GEZONE.md': {
      routes:
        | '/posts/GEZONE'
      views:
        | never
    }
    'pages/posts/LLsif.md': {
      routes:
        | '/posts/LLsif'
      views:
        | never
    }
    'pages/posts/oskarstalbergsGame.md': {
      routes:
        | '/posts/oskarstalbergsGame'
      views:
        | never
    }
    'pages/posts/pageBuilding.md': {
      routes:
        | '/posts/pageBuilding'
      views:
        | never
    }
    'pages/posts/photography.md': {
      routes:
        | '/posts/photography'
      views:
        | never
    }
    'pages/posts/slidev.md': {
      routes:
        | '/posts/slidev'
      views:
        | never
    }
    'pages/posts/smallCCompiler.md': {
      routes:
        | '/posts/smallCCompiler'
      views:
        | never
    }
    'pages/posts/songs.md': {
      routes:
        | '/posts/songs'
      views:
        | never
    }
    'pages/posts/stars.md': {
      routes:
        | '/posts/stars'
      views:
        | never
    }
    'pages/posts/testEchart.md': {
      routes:
        | '/posts/testEchart'
      views:
        | never
    }
    'pages/posts/valaxy.md': {
      routes:
        | '/posts/valaxy'
      views:
        | never
    }
    'pages/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
