/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/about/site_old': RouteRecordInfo<'/about/site_old', '/about/site_old', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/abstract': RouteRecordInfo<'/albums/abstract', '/albums/abstract', Record<never, never>, Record<never, never>>,
    '/albums/animals': RouteRecordInfo<'/albums/animals', '/albums/animals', Record<never, never>, Record<never, never>>,
    '/albums/ff14': RouteRecordInfo<'/albums/ff14', '/albums/ff14', Record<never, never>, Record<never, never>>,
    '/albums/GEZONE': RouteRecordInfo<'/albums/GEZONE', '/albums/GEZONE', Record<never, never>, Record<never, never>>,
    '/albums/green': RouteRecordInfo<'/albums/green', '/albums/green', Record<never, never>, Record<never, never>>,
    '/albums/lives': RouteRecordInfo<'/albums/lives', '/albums/lives', Record<never, never>, Record<never, never>>,
    '/albums/objects': RouteRecordInfo<'/albums/objects', '/albums/objects', Record<never, never>, Record<never, never>>,
    '/albums/sky': RouteRecordInfo<'/albums/sky', '/albums/sky', Record<never, never>, Record<never, never>>,
    '/albums/water': RouteRecordInfo<'/albums/water', '/albums/water', Record<never, never>, Record<never, never>>,
    '/anime/': RouteRecordInfo<'/anime/', '/anime', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/ADFGVXCypher': RouteRecordInfo<'/posts/ADFGVXCypher', '/posts/ADFGVXCypher', Record<never, never>, Record<never, never>>,
    '/posts/bigDataVisualization': RouteRecordInfo<'/posts/bigDataVisualization', '/posts/bigDataVisualization', Record<never, never>, Record<never, never>>,
    '/posts/booksSearch': RouteRecordInfo<'/posts/booksSearch', '/posts/booksSearch', Record<never, never>, Record<never, never>>,
    '/posts/ffhouse': RouteRecordInfo<'/posts/ffhouse', '/posts/ffhouse', Record<never, never>, Record<never, never>>,
    '/posts/ffLadiesDay': RouteRecordInfo<'/posts/ffLadiesDay', '/posts/ffLadiesDay', Record<never, never>, Record<never, never>>,
    '/posts/getColor': RouteRecordInfo<'/posts/getColor', '/posts/getColor', Record<never, never>, Record<never, never>>,
    '/posts/GEZONE': RouteRecordInfo<'/posts/GEZONE', '/posts/GEZONE', Record<never, never>, Record<never, never>>,
    '/posts/LLsif': RouteRecordInfo<'/posts/LLsif', '/posts/LLsif', Record<never, never>, Record<never, never>>,
    '/posts/oskarstalbergsGame': RouteRecordInfo<'/posts/oskarstalbergsGame', '/posts/oskarstalbergsGame', Record<never, never>, Record<never, never>>,
    '/posts/pageBuilding': RouteRecordInfo<'/posts/pageBuilding', '/posts/pageBuilding', Record<never, never>, Record<never, never>>,
    '/posts/photography': RouteRecordInfo<'/posts/photography', '/posts/photography', Record<never, never>, Record<never, never>>,
    '/posts/smallCCompiler': RouteRecordInfo<'/posts/smallCCompiler', '/posts/smallCCompiler', Record<never, never>, Record<never, never>>,
    '/posts/songs': RouteRecordInfo<'/posts/songs', '/posts/songs', Record<never, never>, Record<never, never>>,
    '/posts/stars': RouteRecordInfo<'/posts/stars', '/posts/stars', Record<never, never>, Record<never, never>>,
    '/posts/testEchart': RouteRecordInfo<'/posts/testEchart', '/posts/testEchart', Record<never, never>, Record<never, never>>,
    '/posts/valaxy': RouteRecordInfo<'/posts/valaxy', '/posts/valaxy', Record<never, never>, Record<never, never>>,
    '/slides/': RouteRecordInfo<'/slides/', '/slides', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
